# Interaction parameters
interaction:
  n_samples: 4
  stopping_condition: "never_stop" 
  feedback_type: "nl_feedback"
  n_iter_refinement_steps: 5


# Dataset params
dataset: 
  input_transformation_type: "plain_summary"
  solution_info_type: "full_solution"
  shuffle: True

# User model uses oracle summaries to give asst feedback
user_model:
  model_name: "gpt-4o-mini"
  api_key: "OPENAI_KEY"
  prompt_fn: "prompts/user/self_critique_ir_nl_feedback.yaml"
  include_history: False

# Asst model uses user answers to write code
asst_model:
  model_name: "claude-3.5-sonnet"
  api_key: "CLAUDE_KEY"
  prompt_fn: "prompts/asst/apps_ir_nl_feedback_no_history.yaml"
  include_history: False