output_dir: "output/test_pipeline"

# Dataset params
dataset: 
  name: apps
  input_transformation_type: "fuzzy_question"
  solution_info_type: "1_sentence_summary"
  difficulty: "interview"
  split: "train"
  shuffle: false

# Oracle produces summaries
oracle_model:
  model_name: "claude-3.5-sonnet"
  api_key: "API_KEY"
  prompt_fn: "prompts/oracle.yaml"



