# Interaction parameters
interaction:
  feedback_setting: iter_refinement
  n_iter_refinement_steps: 5
  feedback_type: nl_feedback
  n_samples: 4
  stopping_condition: "never_stop" 

# Dataset params
dataset: 
  input_transformation_type: "plain_summary"
  solution_info_type: "full_solution"
  shuffle: True

# User model uses oracle summaries to give asst feedback
user_model:
  model_name: "claude-3.5-sonnet"
  api_key: "CLAUDE_KEY"
  prompt_fn: "prompts/user/ir_code_feedback.yaml"
  include_history: False


# Asst model uses user answers to write code
asst_model:
  include_history: False
  model_name: "google/gemma-7b-it"
  api_key: "HUGGINGFACE_API_KEY"
  prompt_fn: "prompts/asst/apps_ir_nl_feedback_no_history.yaml"
  n_samples: 2
  cache_dir: '/data/user_data/rshar/hf'
  generation_config:
    do_sample: True
    temperature: 0.9
  stopping_condition:
    n_lines: 50
    n_tokens: 1000



