# Interaction parameters
interaction:
  n_samples: 4
  stopping_condition: "never_stop" 
  n_iter_refinement_steps: 5
  feedback_setting: iter_refinement
  feedback_type: null

# Dataset params
dataset: 
  input_transformation_type: "plain_summary"
  solution_info_type: "full_solution"
  shuffle: True

# Asst model uses user answers to write code
asst_model:
  model_name: "claude-3.5-sonnet"
  api_key: CLAUDE_KEY
  prompt_fn: "prompts/asst/apps_ir_no_feedback.yaml"