
# Interaction parameters
interaction:
  n_samples: 4
  stopping_condition: "never_stop" 

# Dataset params
dataset: 
  input_transformation_type: "vanilla"
  solution_info_type: "full_solution"
  shuffle: True

# Asst model uses user answers to write code
asst_model:
  model_name: "claude-3.5-sonnet"
  api_key: "CLAUDE_API_KEY"
  prompt_fn: "prompts/asst/class_eval_vanilla.yaml"
