# Interaction parameters
interaction:
  feedback_setting: iter_refinement
  n_iter_refinement_steps: 5
  feedback_type: nl_feedback
  n_samples: 4
  stopping_condition: "never_stop" 

# Dataset params
dataset: 
  input_transformation_type: "func_summary"
  solution_info_type: "full_solution"
  shuffle: True

# User model uses oracle summaries to give asst feedback
user_model:
  model_name: "claude-3.5-sonnet"
  api_key: "CLAUDE_KEY"
  prompt_fn: null
  include_history: False


# Asst model uses user answers to write code
asst_model:
  include_history: False
  api_key: "CLAUDE_KEY"
  model_name: "claude-3.5-sonnet"
  prompt_fn: "prompts/asst/classeval_ir_nl_feedback.yaml"
