# Interaction parameters
interaction:
  feedback_setting: iter_refinement
  feedback_type: free_response_answer
  n_samples: 4
  stopping_condition: "never_stop" 
  n_iter_refinement_steps: 5
  history_window: 10

# Dataset params
dataset: 
  n_examples: 3
  input_transformation_type: "plain_summary"
  solution_info_type: "full_solution"
  shuffle: True

# User model uses oracle summaries to give asst feedback
user_model:
  model_name: "gpt-4o-mini"
  api_key: "OPENAI_KEY"
  prompt_fn: "prompts/user/ir_fr_answer.yaml"
  include_history: False

# Asst model uses user answers to write code
asst_model:
  model_name: "gpt-4o-mini"
  api_key: "OPENAI_KEY"
  prompt_fn: "prompts/asst/apps_ir_fr_answer_no_history.yaml"
  include_history: False