
# Interaction parameters
interaction:
  n_samples: 4
  stopping_condition: "never_stop" 

# Dataset params
dataset: 
  input_transformation_type: "vanilla"
  solution_info_type: "full_solution"
  shuffle: True

# Asst model uses user answers to write code
asst_model:
  prompt_fn: "prompts/asst/lcb_baseline.yaml"
  model_name: "reka-core"
  api_key: REKA_KEY
