# Interaction parameters
interaction:
  feedback_setting: iter_refinement
  feedback_type: test_case
  n_samples: 4
  stopping_condition: "never_stop" 
  n_iter_refinement_steps: 5

# Dataset params
dataset: 
  input_transformation_type: "func_summary"
  solution_info_type: "full_solution"
  shuffle: True

# Asst model uses user answers to write code
asst_model:
  model_name: "gpt-4o"
  api_key: "OPEN_AI_API"
  prompt_fn: "prompts/asst/class_eval.yaml"
  include_history: False
