# Interaction parameters
interaction:
  feedback_setting: iter_refinement
  feedback_type: free_response_answer
  n_samples: 4
  stopping_condition: "never_stop" 
  n_iter_refinement_steps: 5

# Dataset params
dataset: 
  n_examples: 3
  input_transformation_type: "func_summary"
  solution_info_type: "full_solution"
  shuffle: True

# User model uses oracle summaries to give asst feedback
user_model:
  model_name: "claude-3.5-sonnet"
  api_key: "CLAUDE_API_KEY"
  prompt_fn: "prompts/user/ir_fr_answer.yaml"
  include_history: False

# Asst model uses user answers to write code
asst_model:
  model_name: "gpt-4o"
  api_key: "OPEN_AI_API"
  prompt_fn: "prompts/asst/classeval_ir_fr_answer.yaml"
  include_history: False
